# Generated by Django 5.0.1 on 2024-01-13 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("system_administration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=20)),
                ("last_name", models.CharField(default="", max_length=20)),
                ("email_address", models.EmailField(default="", max_length=50)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "country_name",
                    models.CharField(default="Kenya (KE) [+254]", max_length=20),
                ),
                ("identification_number", models.CharField(default="", max_length=20)),
                ("phone_number", models.CharField(default="", max_length=25)),
                (
                    "staff_title",
                    models.CharField(
                        choices=[
                            ("mr", "Mr."),
                            ("mrs", "Mrs."),
                            ("miss", "Miss"),
                            ("other", "Other"),
                            ("not_selected", "Not Selected"),
                        ],
                        default="not_selected",
                        max_length=20,
                    ),
                ),
                ("employment_start_date", models.DateField(blank=True, null=True)),
                ("employment_end_date", models.DateField(blank=True, null=True)),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, default="", max_length=25),
                ),
                ("is_profile_set", models.BooleanField(default=False)),
                ("is_head_of_department", models.BooleanField(default=False)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "company_branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="system_administration.companyprofile",
                    ),
                ),
                (
                    "company_department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="system_administration.companydepartment",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Profile",
                "verbose_name_plural": "Staff Profiles",
            },
        ),
    ]
