# Generated by Django 5.0.1 on 2024-01-14 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="staffPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_title", models.CharField(default="", max_length=100)),
                (
                    "position_description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("salary", models.CharField(blank=True, default="0.00", max_length=12)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Staff Position",
                "verbose_name_plural": "Staff Positions",
            },
        ),
        migrations.CreateModel(
            name="WorkingDays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week_identifier",
                    models.CharField(default="0", max_length=1, unique=True),
                ),
                (
                    "working_day_description",
                    models.CharField(default="", max_length=500),
                ),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="is_on_leave",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="staff_number",
            field=models.CharField(default="", max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name="Bonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bonus_title", models.CharField(default="", max_length=20)),
                (
                    "bonus_type",
                    models.CharField(
                        choices=[
                            ("performance_bonus", "Performance Bonus"),
                            ("annual_bonus", "Annual Bonus"),
                            ("retention_bonus", "Retention Bonus"),
                            ("sales_commision", "Sales Commision"),
                            ("attendance_bonus", "Attendance Bonus"),
                            ("other", "Other"),
                            ("not_selected", "Not Selected"),
                        ],
                        default="not_selected",
                        max_length=20,
                    ),
                ),
                ("bonus_amount", models.CharField(default="0.00", max_length=12)),
                ("date_effective_from", models.DateField(blank=True, null=True)),
                ("date_effective_to", models.DateField(blank=True, null=True)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bonuses_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bonuses_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bonus",
                "verbose_name_plural": "Bonuses",
            },
        ),
        migrations.CreateModel(
            name="BonusInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bonuses_value", models.CharField(default="0.00", max_length=12)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "bonus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bonus_items",
                        to="human_resource.bonus",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bonus_instances_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bonus_instances_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deduction_title", models.CharField(default="", max_length=20)),
                ("deduction_description", models.CharField(default="", max_length=500)),
                (
                    "deduction_type",
                    models.CharField(
                        choices=[
                            ("tax", "Tax"),
                            ("insurance", "Insurance"),
                            ("pension", "Pension"),
                            ("other", "Other"),
                            ("not_selected", "Not Selected"),
                        ],
                        default="not_selected",
                        max_length=20,
                    ),
                ),
                (
                    "deduction_module",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("percentage", "Percentage"),
                            ("not_selected", "Not Selected"),
                        ],
                        default="not_selected",
                        max_length=20,
                    ),
                ),
                ("deduction_value", models.CharField(default="0.00", max_length=20)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deductions_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deductions_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeductionInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deductions_value", models.CharField(default="0.00", max_length=12)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deductions_instances_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "deduction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deduction_items",
                        to="human_resource.deduction",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deductions_instances_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrollSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payroll_sheet_title", models.CharField(default="", max_length=100)),
                ("payroll_sheet_number", models.CharField(max_length=50, unique=True)),
                (
                    "payroll_sheet_description",
                    models.CharField(default="", max_length=500),
                ),
                (
                    "payroll_sheet_for_the_month_off",
                    models.CharField(
                        choices=[
                            ("january", "January"),
                            ("february", "February"),
                            ("march", "March"),
                            ("april", "April"),
                            ("may", "May"),
                            ("june", "June"),
                            ("july", "July"),
                            ("august", "August"),
                            ("september", "September"),
                            ("october", "October"),
                            ("november", "November"),
                            ("december", "December"),
                            ("not_selected", "Not Selected"),
                        ],
                        default="not_selected",
                        max_length=100,
                    ),
                ),
                (
                    "payroll_sheet_value",
                    models.CharField(default="0.00", max_length=15),
                ),
                (
                    "payroll_sheet_approved_by_finance",
                    models.BooleanField(default=False),
                ),
                ("payroll_sheet_payment_settled", models.BooleanField(default=False)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_sheets_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_sheets_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_start_date", models.DateField()),
                ("leave_end_date", models.DateField()),
                ("number_of_leave_days", models.CharField(default="", max_length=5)),
                ("leave_department_approval", models.BooleanField(default=False)),
                ("leave_hr_approval", models.BooleanField(default=False)),
                ("leave_active_status", models.BooleanField(default=False)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_leaves_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_leaves_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "staff_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffPayrollInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gross_salary", models.CharField(default="0.00", max_length=12)),
                ("net_salary", models.CharField(default="0.00", max_length=12)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "bonus_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_bonuses",
                        to="human_resource.bonus",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_instances_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "deduction_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_deductions",
                        to="human_resource.deduction",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_instances_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "payroll_sheet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_payroll_items",
                        to="human_resource.payrollsheet",
                    ),
                ),
                (
                    "staff_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="staff_position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="human_resource.staffposition",
            ),
        ),
        migrations.CreateModel(
            name="TimeSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_time", models.DateTimeField()),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "staff_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("working_hours_start", models.TimeField(blank=True, null=True)),
                ("working_hours_end", models.TimeField(blank=True, null=True)),
                (
                    "working_hours_description",
                    models.CharField(default="", max_length=500),
                ),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "working_day",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="human_resource.workingdays",
                    ),
                ),
            ],
        ),
    ]
