# Generated by Django 5.0.1 on 2024-01-19 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "human_resource",
            "0002_staffposition_workingdays_staffprofile_is_on_leave_and_more",
        ),
        ("system_administration", "0004_systemadmincreationstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollsheet",
            name="company_branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="system_administration.companyprofile",
            ),
        ),
    ]
