# Generated by Django 5.0.1 on 2024-01-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "human_resource",
            "0005_rename_payroll_sheet_for_the_month_off_payrollsheet_payroll_sheet_for_the_month_of_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shift_name", models.CharField(default="", max_length=50)),
                ("shift_hours_start", models.TimeField(blank=True, null=True)),
                ("shift_hours_end", models.TimeField(blank=True, null=True)),
                ("shift_description", models.CharField(default="", max_length=500)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="staffleave",
            name="leave_description",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="staffleave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("sick_leave", "Sick Leave"),
                    ("vacation_leave", "Vacation Leave"),
                    ("maternity_leave", "Maternity Leave"),
                    ("paternity_leave", "Paternity Leave"),
                    ("medical_leave", "Medical Leave"),
                    ("bereavement_leave", "Bereavement Leave"),
                    ("other", "Other"),
                    ("not_selected", "Not Selected"),
                ],
                default="not_selected",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workingdays",
            name="work_shift",
            field=models.ManyToManyField(
                blank=True, related_name="workday_shifts", to="human_resource.workshift"
            ),
        ),
        migrations.DeleteModel(
            name="WorkingHours",
        ),
    ]
