# Generated by Django 5.0.1 on 2024-01-26 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0006_workshift_staffleave_leave_description_and_more"),
        (
            "system_administration",
            "0005_remove_companydepartment_company_branch_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="company_branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="system_administration.companybranch",
            ),
        ),
    ]
