# Generated by Django 5.0.1 on 2024-01-26 20:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0007_alter_staffprofile_company_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
