# Generated by Django 5.0.1 on 2024-01-28 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0008_staffprofile_timestamp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_staff_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
