# Generated by Django 5.0.1 on 2024-02-08 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0011_staffposition_company_profile"),
        ("system_administration", "0010_companyprofile_company_super_hr_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonus",
            name="company_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_bonuses",
                to="system_administration.companyprofile",
            ),
        ),
        migrations.AddField(
            model_name="deduction",
            name="company_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_deductions",
                to="system_administration.companyprofile",
            ),
        ),
        migrations.AddField(
            model_name="workshift",
            name="company_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_work_shifts",
                to="system_administration.companyprofile",
            ),
        ),
        migrations.AlterField(
            model_name="staffleave",
            name="staff_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_leave_instances",
                to="human_resource.staffprofile",
            ),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="staff_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_time_sheets",
                to="human_resource.staffprofile",
            ),
        ),
    ]
