# Generated by Django 5.0.1 on 2024-02-09 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "human_resource",
            "0012_bonus_company_profile_deduction_company_profile_and_more",
        ),
        ("system_administration", "0010_companyprofile_company_super_hr_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deduction",
            name="deduction_module",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage"),
                    ("fixed", "Fixed"),
                    ("not_selected", "Not Selected"),
                ],
                default="not_selected",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payrollsheet",
            name="company_branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branch_payroll_sheets",
                to="system_administration.companyprofile",
            ),
        ),
        migrations.AlterField(
            model_name="staffleave",
            name="number_of_leave_days",
            field=models.CharField(default="1", max_length=5),
        ),
    ]
