# Generated by Django 5.0.1 on 2024-02-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0014_alter_payrollsheet_company_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffpayrollinstance",
            name="commissions_total",
            field=models.CharField(default="0.00", max_length=12),
        ),
    ]
