# Generated by Django 5.0.1 on 2024-02-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0016_alter_staffpayrollinstance_bonus_instance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffpayrollinstance",
            name="bonus_instance",
        ),
        migrations.RemoveField(
            model_name="staffpayrollinstance",
            name="deduction_instance",
        ),
        migrations.AddField(
            model_name="staffpayrollinstance",
            name="bonus_instance",
            field=models.ManyToManyField(
                blank=True,
                related_name="staff_bonuses",
                to="human_resource.bonusinstance",
            ),
        ),
        migrations.AddField(
            model_name="staffpayrollinstance",
            name="deduction_instance",
            field=models.ManyToManyField(
                related_name="staff_deductions", to="human_resource.deductioninstance"
            ),
        ),
    ]
