# Generated by Django 5.0.1 on 2024-02-11 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0017_remove_staffpayrollinstance_bonus_instance_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bonusinstance",
            old_name="bonuses_value",
            new_name="bonus_instance_value",
        ),
        migrations.RenameField(
            model_name="deductioninstance",
            old_name="deductions_value",
            new_name="deduction_instance_value",
        ),
    ]
