# Generated by Django 5.0.1 on 2024-02-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0019_remove_staffleave_leave_active_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffleave",
            name="leave_department_approval",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("denied", "Denied"),
                    ("approaved", "Approaved"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staffleave",
            name="leave_hr_approval",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("denied", "Denied"),
                    ("approaved", "Approaved"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staffleave",
            name="leave_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("denied", "Denied"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
