# Generated by Django 5.0.1 on 2024-02-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0020_alter_staffleave_leave_department_approval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffleave",
            name="leave_department_approval",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("denied", "Denied"),
                    ("approved", "Approved"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staffleave",
            name="leave_hr_approval",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("denied", "Denied"),
                    ("approved", "Approved"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
