# Generated by Django 5.0.1 on 2024-02-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0021_alter_staffleave_leave_department_approval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonus",
            name="bonus_description",
            field=models.CharField(default="", max_length=500),
        ),
    ]
