# Generated by Django 5.0.1 on 2024-02-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0023_alter_bonus_bonus_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deduction",
            name="date_effective_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deduction",
            name="date_effective_to",
            field=models.DateField(blank=True, null=True),
        ),
    ]
