# Generated by Django 5.0.1 on 2024-02-17 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0024_deduction_date_effective_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollsheet",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
