# Generated by Django 5.0.1 on 2024-02-18 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0025_payrollsheet_timestamp"),
        ("system_administration", "0010_companyprofile_company_super_hr_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="bank_account_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="bank_account_number",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="kra_pin",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="type_of_employment",
            field=models.CharField(
                choices=[
                    ("not_selected", "Not Selected"),
                    ("contact", "Contract"),
                    ("permanent", "Permanent"),
                ],
                default="not_selected",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Disciplinary_Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disciplinary_incidence_title",
                    models.CharField(default="", max_length=100),
                ),
                (
                    "disciplinary_incidence_description",
                    models.CharField(default="", max_length=500),
                ),
                ("disciplinary_verdict", models.CharField(default="", max_length=100)),
                (
                    "disciplinary_verdict_description",
                    models.CharField(default="", max_length=100),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_disciplinary_records",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Educational_Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualification_title", models.CharField(default="", max_length=100)),
                (
                    "accredition_category",
                    models.CharField(
                        choices=[
                            ("not_selected", "Not Selected"),
                            ("bachelors", "Bachelors"),
                            ("diploma", "Diploma"),
                            ("certificate", "Certificate"),
                        ],
                        default="not_selected",
                        max_length=20,
                    ),
                ),
                (
                    "accrediting_institution",
                    models.CharField(default="", max_length=100),
                ),
                ("year_of_accredition", models.CharField(default="", max_length=10)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_education_qualifications",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Engagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engagement_title", models.CharField(default="", max_length=100)),
                (
                    "engagement_description",
                    models.CharField(default="", max_length=500),
                ),
                (
                    "engagement_effective_from",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "engagement_effective_to",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "company_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_engagements",
                        to="system_administration.companyprofile",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="staff_engagements",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_title", models.CharField(default="", max_length=100)),
                ("task_description", models.CharField(default="", max_length=500)),
                ("task_effective_from", models.DateTimeField(blank=True, null=True)),
                ("task_effective_to", models.DateTimeField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "company_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_tasks",
                        to="system_administration.companyprofile",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="staff_tasks",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Training_Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("training_title", models.CharField(default="", max_length=100)),
                ("training_description", models.CharField(default="", max_length=500)),
                (
                    "training_effective_from",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("training_effective_to", models.DateTimeField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_training_records",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
    ]
