# Generated by Django 5.0.1 on 2024-02-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0026_staffprofile_bank_account_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="nhif_additional_info",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="nhif_number",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="nssf_additional_info",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="nssf_number",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="staff_additional_info",
            field=models.CharField(default="", max_length=500),
        ),
    ]
