# Generated by Django 5.0.1 on 2024-02-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0028_staffprofile_basic_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deduction",
            name="deduction_type",
            field=models.CharField(
                choices=[
                    ("tax", "Tax"),
                    ("insurance", "Insurance"),
                    ("pension", "Pension"),
                    ("loan_repayment", "Loan Repayment"),
                    ("other", "Other"),
                    ("not_selected", "Not Selected"),
                ],
                default="not_selected",
                max_length=20,
            ),
        ),
    ]
