# Generated by Django 5.0.1 on 2024-02-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0029_alter_deduction_deduction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bonus",
            name="bonus_description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
