# Generated by Django 5.0.1 on 2024-02-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0030_alter_bonus_bonus_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deduction",
            name="deduction_description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
