# Generated by Django 5.0.1 on 2024-02-20 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0031_alter_deduction_deduction_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workingdays",
            name="day_of_week_identifier",
            field=models.CharField(default="0", max_length=1),
        ),
        migrations.RemoveField(
            model_name="workingdays",
            name="work_shift",
        ),
        migrations.AddField(
            model_name="workingdays",
            name="work_shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workday_shifts",
                to="human_resource.workshift",
            ),
        ),
    ]
