# Generated by Django 5.0.1 on 2024-02-20 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0032_alter_workingdays_day_of_week_identifier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workingdays",
            name="working_day_description",
        ),
    ]
