# Generated by Django 5.0.1 on 2024-02-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0033_remove_workingdays_working_day_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffleave",
            name="leave_description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="workshift",
            name="shift_description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
