# Generated by Django 5.0.1 on 2024-02-21 13:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0034_alter_staffleave_leave_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplinary_record",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="disciplinary_record",
            name="last_updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="disciplinary_record",
            name="disciplinary_verdict_description",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.CreateModel(
            name="VacancyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vacancy_title", models.CharField(default="", max_length=100)),
                ("vacancy_description", models.CharField(default="", max_length=500)),
                ("vacancy_count", models.CharField(default="1", max_length=10)),
                ("vacancy_deadline", models.DateTimeField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "vacant_position",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_vacancies",
                        to="human_resource.staffposition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "vacancy_record",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancy_applications",
                        to="human_resource.vacancyrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VacantPositionRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requirement_title", models.CharField(default="", max_length=100)),
                (
                    "requirement_description",
                    models.CharField(default="", max_length=500),
                ),
                (
                    "vacancy_record",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancy_requirements",
                        to="human_resource.vacancyrecord",
                    ),
                ),
            ],
        ),
    ]
