# Generated by Django 5.0.1 on 2024-02-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0035_disciplinary_record_created_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="banking_institution_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
