# Generated by Django 5.0.1 on 2024-02-22 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0037_alter_educational_qualification_accredition_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disciplinary_record",
            name="disciplinary_verdict_description",
        ),
    ]
