# Generated by Django 5.0.1 on 2024-02-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "human_resource",
            "0038_remove_disciplinary_record_disciplinary_verdict_description",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplinary_record",
            name="disciplinary_verdict_description",
            field=models.CharField(default="", max_length=500),
        ),
    ]
