# Generated by Django 5.0.1 on 2024-02-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0039_disciplinary_record_disciplinary_verdict_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="staff_additional_info",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
