# Generated by Django 5.0.1 on 2024-02-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0040_alter_staffprofile_staff_additional_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="bank_account_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="bank_account_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="banking_institution_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="nhif_additional_info",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="nhif_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="nssf_additional_info",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="nssf_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
