# Generated by Django 5.0.1 on 2024-02-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0042_alter_training_record_training_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disciplinary_record",
            name="disciplinary_incidence_description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="disciplinary_record",
            name="disciplinary_incidence_title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="disciplinary_record",
            name="disciplinary_verdict",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="disciplinary_record",
            name="disciplinary_verdict_description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
