# Generated by Django 5.0.1 on 2024-02-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "human_resource",
            "0043_alter_disciplinary_record_disciplinary_incidence_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="deduction",
            name="deduction_module",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage"),
                    ("fixed", "Fixed"),
                    ("other", "Other"),
                    ("not_selected", "Not Selected"),
                ],
                default="not_selected",
                max_length=20,
            ),
        ),
    ]
