# Generated by Django 5.0.1 on 2024-02-25 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0045_staffbonusscheme_staffdeductionscheme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffbonusscheme",
            name="bonus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bonus_schemes",
                to="human_resource.bonus",
            ),
        ),
        migrations.AlterField(
            model_name="staffdeductionscheme",
            name="deduction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deduction_schemes",
                to="human_resource.deduction",
            ),
        ),
    ]
