# Generated by Django 5.0.1 on 2024-02-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "human_resource",
            "0047_payrollsheet_payroll_sheet_total_bonus_value_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payrollsheet",
            name="payroll_sheet_number",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
    ]
