# Generated by Django 5.0.1 on 2024-02-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0048_alter_payrollsheet_payroll_sheet_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payrollsheet",
            name="payroll_sheet_description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
