# Generated by Django 5.0.1 on 2024-03-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0049_alter_payrollsheet_payroll_sheet_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffpayrollinstance",
            name="is_prorated",
            field=models.BooleanField(default=False),
        ),
    ]
