# Generated by Django 5.0.1 on 2024-03-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0050_staffpayrollinstance_is_prorated"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffpayrollinstance",
            name="pro_rate_factor",
            field=models.CharField(default="0.00", max_length=12),
        ),
    ]
