# Generated by Django 5.0.1 on 2024-03-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0052_alter_staffpayrollinstance_pro_rate_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="personal_email",
            field=models.EmailField(blank=True, default="", max_length=100),
        ),
    ]
