# Generated by Django 5.0.1 on 2024-03-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0053_staffprofile_personal_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="bank_branch_code",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="bank_branch_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="bank_swift_code",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
