# Generated by Django 5.0.1 on 2024-03-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0054_staffprofile_bank_branch_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffleave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("sick_leave", "Sick Leave"),
                    ("annual_leave", "Annual Leave"),
                    ("vacation_leave", "Vacation Leave"),
                    ("maternity_leave", "Maternity Leave"),
                    ("paternity_leave", "Paternity Leave"),
                    ("medical_leave", "Medical Leave"),
                    ("bereavement_leave", "Bereavement Leave"),
                    ("other", "Other"),
                    ("not_selected", "Not Selected"),
                ],
                default="not_selected",
                max_length=20,
            ),
        ),
    ]
