# Generated by Django 5.0.1 on 2024-01-19 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "human_resource",
            "0002_staffposition_workingdays_staffprofile_is_on_leave_and_more",
        ),
        ("system_administration", "0002_companybranch_recycle_bin_and_more"),
        ("warehouse_management", "0003_inventory_minimum_stock_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_order_number", models.CharField(max_length=50, unique=True)),
                (
                    "customer_order_type",
                    models.CharField(
                        choices=[
                            ("order_online", "Order Online"),
                            ("order_offline", "Order Offline"),
                            ("not_selected", "Not Selected"),
                        ],
                        default="not_selected",
                        max_length=20,
                    ),
                ),
                (
                    "customer_order_description",
                    models.CharField(default="", max_length=500),
                ),
                (
                    "customer_order_total_gross_value",
                    models.CharField(default="0.00", max_length=50),
                ),
                (
                    "customer_order_total_discount",
                    models.CharField(default="0.00", max_length=50),
                ),
                (
                    "customer_order_total_net_value",
                    models.CharField(default="0.00", max_length=50),
                ),
                ("customer_order_approved", models.BooleanField(default=False)),
                (
                    "customer_order_fulfilled_for_transit",
                    models.BooleanField(default=False),
                ),
                (
                    "customer_ordered_delivered_to_destination",
                    models.BooleanField(default=False),
                ),
                (
                    "customer_order_picked_by_customer",
                    models.BooleanField(default=False),
                ),
                (
                    "customer_order_cancelled_by_customer",
                    models.BooleanField(default=False),
                ),
                (
                    "customer_order_cancelled_by_sales_team",
                    models.BooleanField(default=False),
                ),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                ("expected_delivery_date", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_offline_order_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_offline_order_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.CharField(default="0", max_length=15)),
                ("price_per_item", models.CharField(default="0.00", max_length=50)),
                ("discount_per_item", models.CharField(default="0.00", max_length=50)),
                ("gross_subtotal", models.CharField(default="0.00", max_length=50)),
                ("total_discount", models.CharField(default="0.00", max_length=50)),
                ("net_subtotal", models.CharField(default="0.00", max_length=50)),
                ("sales_item_order_fulfilled", models.BooleanField(default=False)),
                (
                    "customer_order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_order_items",
                        to="sales_and_marketing.customerorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerOrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_number", models.CharField(max_length=50, unique=True)),
                ("payment_amount", models.CharField(default="0.00", max_length=50)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("m_pesa", "M-Pesa"),
                            ("cash", "Cash"),
                            ("credit_card", "Credit Card"),
                            ("not_selected", "Not Selected"),
                        ],
                        default="not_selected",
                        max_length=20,
                    ),
                ),
                ("payer_account_number", models.CharField(default="", max_length=30)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "customer_order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_order_payments",
                        to="sales_and_marketing.customerorder",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_first_name", models.CharField(default="", max_length=20)),
                ("customer_last_name", models.CharField(default="", max_length=20)),
                ("email_address", models.EmailField(default="", max_length=50)),
                ("phone_number", models.CharField(default="", max_length=25)),
                (
                    "customer_title",
                    models.CharField(
                        choices=[
                            ("mr", "Mr."),
                            ("mrs", "Mrs."),
                            ("miss", "Miss"),
                            ("other", "Other"),
                            ("not_selected", "Not Selected"),
                        ],
                        default="not_selected",
                        max_length=20,
                    ),
                ),
                ("is_profile_set", models.BooleanField(default=False)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Profile",
                "verbose_name_plural": "Customer Profiles",
            },
        ),
        migrations.AddField(
            model_name="customerorder",
            name="customer_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sales_and_marketing.customerprofile",
            ),
        ),
        migrations.CreateModel(
            name="CustomerShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipping_address", models.CharField(default="", max_length=100)),
                ("shipping_town", models.CharField(default="", max_length=50)),
                (
                    "customer_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales_and_marketing.customerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItemReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recycle_bin", models.BooleanField(default=False)),
                ("refund_requested", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                ("date_of_return", models.DateField()),
                (
                    "customer_order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_order_items_return",
                        to="sales_and_marketing.customerorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_brand_name",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "product_brand_description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_brands",
                        to="warehouse_management.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_name",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "component_quantity",
                    models.CharField(blank=True, default="1", max_length=12),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_components",
                        to="warehouse_management.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage_discount", "Percentage Discount"),
                            ("fixed_discount", "Fixed Discount"),
                            ("not_selected", "Not Selected"),
                        ],
                        default="not_selected",
                        max_length=20,
                    ),
                ),
                ("discount_value", models.CharField(default="0.00", max_length=5)),
                (
                    "product",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_discount",
                        to="warehouse_management.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductFeaturesCatalogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_feature_title",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_features",
                        to="warehouse_management.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductFeaturesAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_attribute_title",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "feature_attribute_description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "product_feature_catalogue",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_feature_attributes",
                        to="sales_and_marketing.productfeaturescatalogue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImageCatalogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_image", models.ImageField(blank=True, upload_to="")),
                (
                    "image_attribute",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("use_as_main_image", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_images",
                        to="warehouse_management.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image Catalogue",
                "verbose_name_plural": "Product Image Catalogues",
            },
        ),
        migrations.CreateModel(
            name="ProductPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_net_price", models.CharField(default="0.00", max_length=50)),
                (
                    "product",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_pricing",
                        to="warehouse_management.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refund_amount", models.CharField(default="0.00", max_length=50)),
                ("refund_approved", models.BooleanField(default=False)),
                ("refund_fullfilled", models.BooleanField(default=False)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "order_item_return",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items_requesting_refunds",
                        to="sales_and_marketing.orderitemreturn",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_refunds",
                        to="sales_and_marketing.customerorderpayment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason_for_return", models.CharField(default="", max_length=500)),
                (
                    "order_item_return",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items_return",
                        to="sales_and_marketing.orderitemreturn",
                    ),
                ),
                (
                    "ordered_item_returned",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_items_returned",
                        to="sales_and_marketing.customerorderitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleOutlet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_outlet_name",
                    models.CharField(default="", max_length=50, unique=True),
                ),
                ("sale_outlet_location", models.CharField(default="", max_length=50)),
                (
                    "sale_outlet_contact_phone",
                    models.CharField(default="", max_length=25),
                ),
                (
                    "sale_outlet_description",
                    models.CharField(default="", max_length=500),
                ),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "company_branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="system_administration.companyprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_outlet_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_outlet_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.CharField(default="0", max_length=15)),
                ("minimum_stock_level", models.CharField(default="0", max_length=15)),
                (
                    "sales_inventory_description",
                    models.CharField(default="", max_length=500),
                ),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_inventory_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_inventory_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_sales_inventories",
                        to="warehouse_management.product",
                    ),
                ),
                (
                    "sale_outlet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_outlet_sales_inventory",
                        to="sales_and_marketing.saleoutlet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Inventory",
                "verbose_name_plural": "Sales Inventories",
            },
        ),
        migrations.AddField(
            model_name="customerorderitem",
            name="inventory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_order_products",
                to="sales_and_marketing.salesinventory",
            ),
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sales_order_number", models.CharField(max_length=50, unique=True)),
                (
                    "sales_order_description",
                    models.CharField(default="", max_length=500),
                ),
                ("sales_order_approved", models.BooleanField(default=False)),
                ("sales_order_fulfilled", models.BooleanField(default=False)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_order_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_order_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "sale_outlet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_outlet_sales_order",
                        to="sales_and_marketing.saleoutlet",
                    ),
                ),
                (
                    "warehouse",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_order_warehouse",
                        to="warehouse_management.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesOrderItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.CharField(default="0", max_length=15)),
                ("sales_item_order_fulfilled", models.BooleanField(default=False)),
                (
                    "inventory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_sales_order_items",
                        to="warehouse_management.inventory",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_order_sales_items",
                        to="sales_and_marketing.salesorder",
                    ),
                ),
            ],
        ),
    ]
