# Generated by Django 5.0.1 on 2024-01-24 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0006_workshift_staffleave_leave_description_and_more"),
        ("sales_and_marketing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commission_title", models.CharField(default="", max_length=50)),
                (
                    "commission_description",
                    models.CharField(default="", max_length=500),
                ),
                (
                    "commission_rate_percentage",
                    models.CharField(default="0", max_length=15),
                ),
                ("commission_period_start_date", models.DateField()),
                ("commission_period_end_date", models.DateField()),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_commission_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_commission_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "sales_person",
                    models.ManyToManyField(
                        related_name="sales_commission_sales_persons",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
    ]
