# Generated by Django 5.0.1 on 2024-01-28 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_and_marketing", "0003_alter_customerprofile_user"),
        ("system_administration", "0006_companydepartment_company_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="company_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_customers",
                to="system_administration.companyprofile",
            ),
        ),
    ]
