# Generated by Django 5.0.1 on 2024-02-09 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resource", "0014_alter_payrollsheet_company_branch"),
        ("sales_and_marketing", "0004_customerprofile_company_profile"),
        ("system_administration", "0010_companyprofile_company_super_hr_created"),
        ("warehouse_management", "0005_remove_stocktransaction_product_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salescommission",
            old_name="commission_rate_percentage",
            new_name="commission_value",
        ),
        migrations.AddField(
            model_name="customerorder",
            name="sales_person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_offline_sales_representative",
                to="human_resource.staffprofile",
            ),
        ),
        migrations.AddField(
            model_name="salescommission",
            name="commission_module",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage"),
                    ("fixed", "Fixed"),
                    ("not_selected", "Not Selected"),
                ],
                default="not_selected",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="salescommission",
            name="product",
            field=models.ManyToManyField(
                related_name="product_sales_commissions",
                to="warehouse_management.product",
            ),
        ),
        migrations.CreateModel(
            name="CommissionSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_sheet_title",
                    models.CharField(default="", max_length=100),
                ),
                (
                    "commission_sheet_number",
                    models.CharField(max_length=50, unique=True),
                ),
                (
                    "commission_sheet_description",
                    models.CharField(default="", max_length=500),
                ),
                (
                    "commission_sheet_for_the_month_of",
                    models.CharField(
                        choices=[
                            ("january", "January"),
                            ("february", "February"),
                            ("march", "March"),
                            ("april", "April"),
                            ("may", "May"),
                            ("june", "June"),
                            ("july", "July"),
                            ("august", "August"),
                            ("september", "September"),
                            ("october", "October"),
                            ("november", "November"),
                            ("december", "December"),
                            ("not_selected", "Not Selected"),
                        ],
                        default="not_selected",
                        max_length=100,
                    ),
                ),
                (
                    "commission_sheet_for_the_year",
                    models.CharField(default="2024", max_length=15),
                ),
                (
                    "commission_sheet_value",
                    models.CharField(default="0.00", max_length=15),
                ),
                (
                    "commission_sheet_approved_by_finance",
                    models.BooleanField(default=False),
                ),
                (
                    "commission_sheet_payment_settled",
                    models.BooleanField(default=False),
                ),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "company_branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branch_commission_sheets",
                        to="system_administration.companybranch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_sheets_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_sheets_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommissionSheetInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commission_value", models.CharField(default="0.00", max_length=12)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "commission_sheet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_items",
                        to="sales_and_marketing.commissionsheet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_items_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "customer_order",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_order_commissions",
                        to="sales_and_marketing.customerorder",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_items_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "staff_payroll_instance",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_payroll_instance_commissions",
                        to="human_resource.staffpayrollinstance",
                    ),
                ),
            ],
        ),
    ]
