from django.urls import path
from . import views
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('human-resource-dashboard/', views.human_resource_dashboard),
    path('edit-staff-profile/', views.edit_staff_profile),
    path('create-staff-position/', views.create_staff_position),
    path('edit-staff-position/', views.edit_staff_position),
    path('super-hr-get-staff-profiles-to-set_up/',
         views.super_hr_get_staff_profiles_to_set_up),
    path('create-bonus/',
         views.create_bonus),
    path('create-deduction/',
         views.create_deduction),
    path('create-work-shift/',
         views.create_work_shift),
    path('create-staff-leave/',
         views.create_staff_leave),
    path('create-educational-qualification/',
         views.create_educational_qualification),
    path('create-training-record/',
         views.create_training_record),
    path('create-disciplinary-record/',
         views.create_disciplinary_record),
    path('create-task/',
         views.create_task),
    path('create-engagement/',
         views.create_engagement),
    path('create-vacancy-record/',
         views.create_vacancy_record),
#     path('create-vacancy-record/',
#          views.create_vacancy_record),
    path('edit-staff-financial-info/',
         views.edit_staff_financial_info),
    path('edit-educational-qualification/',
         views.edit_educational_qualification),
    path('edit-training-record/',
         views.edit_training_record),
    path('create-payroll-sheet/',
         views.create_payroll_sheet),
    path('edit-payroll-sheet/', views.edit_payroll_sheet),
    path('get-my-profile-details/', views.get_my_profile_details),
    path('edit-staff-detail-mini/', views.edit_staff_detail_mini),
    path('change-password/', views.change_password),
    path('delete-bonus/', views.delete_bonus),
    path('delete-deduction/', views.delete_deduction),
    path('delete-payroll-sheet/', views.delete_payroll_sheet),
    path('delete-staff-position/', views.delete_staff_position),
    path('delete-staff-profile/', views.delete_staff_profile),
    path('delete-work-shift/', views.delete_work_shift),
    path('delete-staff-leave/', views.delete_staff_leave),
]
