# Generated by Django 5.0.1 on 2024-01-19 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "warehouse_management",
            "0002_purchaserequisition_purchase_requisition_approved_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="minimum_stock_level",
            field=models.CharField(default="0", max_length=15),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="product",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_inventories",
                to="warehouse_management.product",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="warehouse",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_inventories",
                to="warehouse_management.warehouse",
            ),
        ),
    ]
