# Generated by Django 5.0.1 on 2024-01-21 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_management", "0004_stockrequisition_stockrequisitioninstance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocktransaction",
            name="product",
        ),
        migrations.RemoveField(
            model_name="stocktransaction",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="stocktransaction",
            name="warehouse",
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="recipient_warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipient_warehouse_stock_transactions",
                to="warehouse_management.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="source_warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_warehouse_stock_transactions",
                to="warehouse_management.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="stock_transaction_added_to_inventory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="stock_transaction_number",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="stock_transaction_reference",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.CreateModel(
            name="StockTransactionInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.CharField(default="0", max_length=15)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_stock_transactions",
                        to="warehouse_management.product",
                    ),
                ),
                (
                    "stock_transaction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_transaction_instannces",
                        to="warehouse_management.stocktransaction",
                    ),
                ),
            ],
        ),
    ]
