# Generated by Django 5.0.1 on 2024-03-06 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_management", "0005_remove_stocktransaction_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_inventories",
                to="warehouse_management.warehouse",
            ),
        ),
    ]
