# Generated by Django 5.0.1 on 2024-03-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_management", "0008_alter_warehouse_company_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="inventory_description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="purchase_requisition_description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="stockrequisition",
            name="stock_requisition_description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="warehouse_description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
