# Generated by Django 5.0.1 on 2024-03-15 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_management", "0009_alter_category_category_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_inventories",
                to="warehouse_management.product",
            ),
        ),
    ]
