# Generated by Django 5.0.1 on 2024-03-15 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_management", "0010_alter_inventory_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransactioninstance",
            name="stock_transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_transaction_instances",
                to="warehouse_management.stocktransaction",
            ),
        ),
    ]
