# Generated by Django 5.0.1 on 2024-03-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_management", "0012_alter_equipment_equipment_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("operational", "Operational"),
                    ("under_maintenance", "Under Maintenance"),
                    ("decommisioned", "Decommisioned"),
                    ("not_selected", "Not Selected"),
                ],
                default="not_selected",
                max_length=20,
            ),
        ),
    ]
