# Generated by Django 5.0.1 on 2024-03-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_management", "0013_alter_equipment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="equipment_quantity",
            field=models.CharField(default="1", max_length=15),
        ),
    ]
