# Generated by Django 5.0.1 on 2024-03-18 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_management", "0015_remove_equipment_equipment_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
