# Generated by Django 5.0.1 on 2024-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_management", "0016_product_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit_of_measurement",
            field=models.CharField(
                choices=[
                    ("kilowatts", "Kilowatts"),
                    ("piece", "Piece"),
                    ("box", "Box"),
                    ("pallet", "Pallet"),
                    ("metre", "Metre"),
                    ("kg", "Kg"),
                    ("litre", "Litre"),
                    ("other", "Other"),
                    ("not_selected", "Not Selected"),
                ],
                default="not_selected",
                max_length=20,
            ),
        ),
    ]
