# Generated by Django 5.0.1 on 2024-03-21 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "warehouse_management",
            "0018_alter_stocktransaction_stock_transaction_reference",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
