# Generated by Django 5.0.1 on 2024-01-13 09:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "company_serial_number",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=100
                    ),
                ),
                (
                    "company_description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "company_postal_address",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "company_country_location",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "company_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "company_preferred_currency",
                    models.CharField(
                        choices=[
                            ("usd", "USD"),
                            ("gbp", "GBP"),
                            ("eur", "EUR"),
                            ("kes", "KES"),
                            ("not_selected", "Not Selected"),
                        ],
                        default="kes",
                        max_length=30,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profiles",
            },
        ),
        migrations.CreateModel(
            name="CompanyDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department_name",
                    models.CharField(
                        choices=[
                            ("system_and_administration", "System and Administration"),
                            ("procurement", "Procurement"),
                            ("human_resource_management", "Human Resource Management"),
                            ("warehouse_management", "Warehouse Management"),
                            ("sales_and_marketing", "Sales and Marketing"),
                            ("finance_and_accounting", "Finance and Accounting"),
                            ("support_services", "Support Services"),
                            ("not_selected", "Not Selected"),
                        ],
                        default="not_selected",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "department_description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "company_branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="system_administration.companyprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Department",
                "verbose_name_plural": "Company Departments",
            },
        ),
        migrations.CreateModel(
            name="CompanyBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "branch_description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "branch_county_location",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "branch_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("branch_active", models.BooleanField(default=True)),
                ("main_branch", models.BooleanField(default=False)),
                (
                    "branch_mpesa_consumer_key",
                    models.CharField(blank=True, default="", max_length=150, null=True),
                ),
                (
                    "branch_mpesa_consumer_secret",
                    models.CharField(blank=True, default="", max_length=150, null=True),
                ),
                (
                    "branch_mpesa_business_short_code",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "branch_mpesa_password",
                    models.CharField(blank=True, default="", max_length=150, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "company_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system_administration.companyprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Branch",
                "verbose_name_plural": "Company Branches",
            },
        ),
    ]
