# Generated by Django 5.0.1 on 2024-01-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_administration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companybranch",
            name="recycle_bin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="companydepartment",
            name="recycle_bin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="recycle_bin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="companydepartment",
            name="department_name",
            field=models.CharField(
                choices=[
                    ("system_and_administration", "System and Administration"),
                    ("procurement", "Procurement"),
                    ("human_resource_management", "Human Resource Management"),
                    ("warehouse_management", "Warehouse Management"),
                    ("sales_and_marketing", "Sales and Marketing"),
                    ("finance_and_accounting", "Finance and Accounting"),
                    ("support_services", "Support Services"),
                    ("management", "Management"),
                    ("not_selected", "Not Selected"),
                ],
                default="not_selected",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="company_serial_number",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=100, unique=True
            ),
        ),
    ]
