# Generated by Django 5.0.1 on 2024-01-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_administration", "0002_companybranch_recycle_bin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="company_profile_set",
            field=models.BooleanField(default=True),
        ),
    ]
