# Generated by Django 5.0.1 on 2024-01-28 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "system_administration",
            "0005_remove_companydepartment_company_branch_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="companydepartment",
            name="company_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_departments",
                to="system_administration.companyprofile",
            ),
        ),
        migrations.AlterField(
            model_name="companybranch",
            name="company_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_branches",
                to="system_administration.companyprofile",
            ),
        ),
    ]
