# Generated by Django 5.0.1 on 2024-02-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_administration", "0006_companydepartment_company_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="company_phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
