# Generated by Django 5.0.1 on 2024-02-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_administration", "0007_alter_companyprofile_company_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="company_country_location",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="company_phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
