# Generated by Django 5.0.1 on 2024-03-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_administration", "0010_companyprofile_company_super_hr_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="company_serial_number",
            field=models.CharField(blank=True, default="", max_length=100, unique=True),
        ),
    ]
