# Generated by Django 5.0.1 on 2024-01-19 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "human_resource",
            "0002_staffposition_workingdays_staffprofile_is_on_leave_and_more",
        ),
        ("procurement", "0001_initial"),
        ("sales_and_marketing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartOfAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=100, unique=True)),
                ("account_number", models.CharField(max_length=50, unique=True)),
                ("account_descriptions", models.CharField(default="", max_length=500)),
                ("running_balance", models.CharField(default="0.00", max_length=50)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_account_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_account_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deposit_number", models.CharField(max_length=50, unique=True)),
                (
                    "deposit_source",
                    models.CharField(
                        choices=[
                            ("sales_revenue", "Sales Revenue"),
                            ("loans", "Loans"),
                            ("other", "Other"),
                            ("not_selected", "Not Selected"),
                        ],
                        default="not_selected",
                        max_length=20,
                    ),
                ),
                ("deposit_amount", models.CharField(default="0.00", max_length=50)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deposit_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deposit_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expense_number", models.CharField(max_length=50, unique=True)),
                ("expense_title", models.CharField(default="", max_length=100)),
                ("expense_description", models.CharField(default="", max_length=500)),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("purchase_expense", "Purchase Expense"),
                            ("salary_expense", "Salary Expense"),
                            ("utility_expense", "Utility Expense"),
                            ("rent_expense", "Rent Expense"),
                            ("operations_expense", "Operations Expense"),
                            ("refund_expense", "Refund Expense"),
                            ("tax_and_license_expense", "Tax and License Expense"),
                            ("other", "Other"),
                            ("not_selected", "Not Selected"),
                        ],
                        default="not_selected",
                        max_length=25,
                    ),
                ),
                ("expense_amount", models.CharField(default="0.00", max_length=50)),
                ("expense_approved", models.BooleanField(default=False)),
                ("expense_settled", models.BooleanField(default=False)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "expense_approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_approved_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "payroll_sheet",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_sheet_expense",
                        to="human_resource.payrollsheet",
                    ),
                ),
                (
                    "purchase_order",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_order_expense",
                        to="procurement.purchaseorder",
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_expense",
                        to="sales_and_marketing.refund",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_number", models.CharField(max_length=50, unique=True)),
                (
                    "transaction_mode",
                    models.CharField(
                        choices=[
                            ("inflow", "Inflow"),
                            ("outflow", "Outflow"),
                            ("not_selected", "Not Selected"),
                        ],
                        default="not_selected",
                        max_length=20,
                    ),
                ),
                ("transaction_amount", models.CharField(default="0.00", max_length=50)),
                ("transaction_reference", models.CharField(default="", max_length=50)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_transactions",
                        to="finance_and_accounting.chartofaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "deposit",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deposit_transaction",
                        to="finance_and_accounting.deposit",
                    ),
                ),
                (
                    "expense",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_transaction",
                        to="finance_and_accounting.expense",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
        ),
    ]
