# Generated by Django 5.0.1 on 2024-01-14 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "human_resource",
            "0002_staffposition_workingdays_staffprofile_is_on_leave_and_more",
        ),
        (
            "warehouse_management",
            "0002_purchaserequisition_purchase_requisition_approved_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_value_overall",
                    models.CharField(default="0.00", max_length=15),
                ),
                ("purchase_order_approved", models.BooleanField(default=False)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_order_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_order_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "purchase_order_approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_order_approved_by",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(default="", max_length=100, unique=True),
                ),
                ("supplier_phone", models.CharField(max_length=15)),
                ("supplier_email", models.EmailField(default="", max_length=50)),
                ("supplier_address", models.CharField(default="", max_length=100)),
                ("supplier_description", models.CharField(default="", max_length=500)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "supplied_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="supplier_products",
                        to="warehouse_management.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductPurchaseInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_value_per_unit",
                    models.CharField(default="0.00", max_length=15),
                ),
                (
                    "purchase_value_overall",
                    models.CharField(default="0.00", max_length=15),
                ),
                (
                    "purchase_amount_paid_to_supplier",
                    models.CharField(default="0.00", max_length=15),
                ),
                ("supplier_payment_settled", models.BooleanField(default=False)),
                ("product_purchase_delivered", models.BooleanField(default=False)),
                ("quantity_delivered", models.CharField(default="0", max_length=15)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_purchase_instance_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_purchase_instance_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "purchase_requisition_instance",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_requisition_product_instances",
                        to="warehouse_management.purchaserequisitioninstance",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_order_product_instances",
                        to="procurement.purchaseorder",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_product_purchase_instances",
                        to="procurement.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Purchase Instance",
                "verbose_name_plural": "Product Purchase Instances",
            },
        ),
    ]
