# Generated by Django 5.0.1 on 2024-01-21 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "human_resource",
            "0005_rename_payroll_sheet_for_the_month_off_payrollsheet_payroll_sheet_for_the_month_of_and_more",
        ),
        ("procurement", "0001_initial"),
        ("warehouse_management", "0004_stockrequisition_stockrequisitioninstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="purchase_order_number",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="productpurchaseinstance",
            name="purchase_requisition_instance",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_requisition_product_instances",
                to="warehouse_management.purchaserequisitioninstance",
            ),
        ),
        migrations.CreateModel(
            name="StockOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_order_number",
                    models.CharField(default="", max_length=50, unique=True),
                ),
                ("stock_order_approved", models.BooleanField(default=False)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_order_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_order_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "stock_order_approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_order_approved_by",
                        to="human_resource.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Order",
                "verbose_name_plural": "Stock Orders",
            },
        ),
        migrations.CreateModel(
            name="StockOrderInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_order_item_delivered", models.BooleanField(default=False)),
                ("quantity_delivered", models.CharField(default="0", max_length=15)),
                ("recycle_bin", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_order_instance_created_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_order_instance_last_updated_by",
                        to="human_resource.staffprofile",
                    ),
                ),
                (
                    "stock_order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_order_product_instances",
                        to="procurement.purchaseorder",
                    ),
                ),
                (
                    "stock_requisition_instance",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_requisition_product_instances",
                        to="warehouse_management.stockrequisitioninstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Order Instance",
                "verbose_name_plural": "Stock Order Instances",
            },
        ),
    ]
