# Generated by Django 5.0.1 on 2024-03-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0006_productpurchaseinstance_quantity_purchased"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockorderinstance",
            name="quantity_ordered",
            field=models.CharField(default="0", max_length=15),
        ),
    ]
